apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ include "server.llama.cpp.fullname" . }}-download-model
  labels:
    {{- include "server.llama.cpp.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ include "server.llama.cpp.fullname" . }}-download-model
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "server.llama.cpp.labels" . | nindent 8 }}
        {{- with .Values.jobLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ include "server.llama.cpp.fullname" . }}-download-model
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.images.downloader.repository }}:{{ .Values.images.downloader.name }}{{if  .Values.images.downloader.tag }}-{{end}}{{ .Values.images.downloader.tag }}
          env:
            - name: MODEL_PATH
              value: {{ .Values.model.path }}
            - name: MODEL_FILE
              value: {{  regexReplaceAll "(.*/)?([^/]+).gguf" .Values.model.file "${2}.gguf" }}
            - name: MODEL_SHA256
              value: {{ .Values.model.sha256 }}
            - name: MODEL_DOWNLOAD_REPO
              value: {{ .Values.model.repo }}
            - name: MODEL_DOWNLOAD_FILE
              value: {{ .Values.model.file }}
          command:
            - sh
            - -c
          args:
            - >
              set -eux;
              if ! echo "${MODEL_SHA256} *${MODEL_PATH}/${MODEL_FILE}" | sha256sum -c -s - ; then
                wget -q -c -O ${MODEL_PATH}/${MODEL_FILE} https://huggingface.co/${MODEL_DOWNLOAD_REPO}/resolve/main/${MODEL_DOWNLOAD_FILE};
              fi
          volumeMounts:
            - mountPath: {{ .Values.model.path }}
              name: models
      restartPolicy: OnFailure
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: {{ include "server.llama.cpp.fullname" . }}
            readOnly: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}