{{- if .Values.server.metrics }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "server.llama.cpp.fullname" . }}
  labels:
    {{- include "server.llama.cpp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "server.llama.cpp.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: http
      interval: 30s
      path: /metrics
{{end}}