kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "server.llama.cpp.fullname" . }}
  labels:
    {{- include "server.llama.cpp.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.model.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (not empty .Values.persistence.storageClass) }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}